### ISSUE TITLE
Investigate options for testing frameworks

### ISSUE THREAD

**Issue by okjuan** [Wubbadub/ClubHub#32] opened 2016-10-18 00:12 UTC
**Feature Name**
Testing

**Description**
Find a testing framework to use throughout development.

**Requires**
- [requirement 1]

**Subtask Breakdown**
- [ ] Outline requirements for testing framework
- [ ] Find a list of candidates that adhere to requirements

**Due**
Milestone []

**Time Estimation:**
[]hrs.

**Comment by hwkr** [comment] 2016-10-22 00:18
Closing this as duplicate of #33.

**Closed as completed by hwkr** 2016-10-22 00:18 UTC
Labels: chore, development
